### ISSUE TITLE
Cannot read property 'UriResolver' of undefined

### ISSUE THREAD

**Issue by haraldini** [EthWorks/Waffle#85] opened 2019-02-25 14:04 UTC
Just did a simple out of the box yarn install on an existing project.  `npx waffle` just throws this error on a very basic test: `Cannot read property 'UriResolver' of undefined`

**Comment by snario** [comment] 2019-02-25 18:36
Also getting this @marekkirejczyk

**Comment by marekkirejczyk** [comment] 2019-02-26 15:54
Looking into it

**Comment by snario** [comment] 2019-02-26 15:56
This patch fixed it on our repo:
https://github.com/counterfactual/monorepo/blob/c262920ab4b170a3b732e568ee77c7cc5b1aeea4/patches/%40resolver-engine%2Bimports-fs%2B0.3.2.patch#L1-L22

**Comment by marekkirejczyk** [comment] 2019-02-26 17:27
I have hard times reproduction. I already looked into @snario repo, I think it might be related to truffle-flattener that requires a different version of @resolver-engine/imports-fs.

@haraldini Can you link repo, or yarn.lock file, so I can look into it?

I'll dig deeper tomorrow.

**Comment by haraldini** [comment] 2019-02-27 09:41
I moved on and didn't keep a snapshop I'm afraid. I was using ZepKit as a starting point if that that might help somewhat: `truffle unbox zeppelinos/zepkit
`

**Comment by Amxx** [comment] 2019-06-29 11:14
Also getting the same error is some cases:
$ waffle waffle.js
→ ok
$ yarn build ("build": "waffle waffle.json")
→ not ok

Happens on kitsune-contract and universalloginsdk

**Comment by Amxx** [comment] 2019-06-29 11:17
@snario 's fix works for me

**Comment by cehali** [comment] 2019-08-20 11:29
Hi,
I recreated this error and it turns out that it is a problem with zos-lib. Zos-lib requires truffle-flattener which requires an older version of @resolver-engine/core. Openzeppelin had the same problem: https://github.com/OpenZeppelin/openzeppelin-sdk/pull/1059. Funny thing is that using npm instead of yarn install the newest version of @resolver-engine/core. So there are two solutions, either you can use npm instead of yarn (I believe it is not desired) or you can add `"@resolver-engine/core": "^0.3.3"` to your dependency to force yarn to install the newest and compatible version. I added this dependency to Amxx code and I could build and run tests without problem mentioned in this issue.

**Comment by marekkirejczyk** [comment] 2019-12-09 15:11
Closing, please reopen if it is still an issue

**Closed by marekkirejczyk** 2019-12-09 15:11 UTC
