### ISSUE TITLE
Matching any argument in a mock using withArgs()

### ISSUE THREAD

**Issue by partywave** [EthWorks/Waffle#361] opened 2020-09-18 12:28 UTC
Please advise if there is a way to match anything in the list of arguments supplied to the `Contract::withArgs` method.

**Comment by marekkirejczyk** [comment] 2020-09-22 09:41
Do you mean sth like:
```ts
await expect(token.transfer(walletTo.address, 7))
  .to.emit(token, 'Transfer')
  .withArgs(/.*/, walletTo.address, 7);
```

There is currently no way to match any argument and we don't plan to add such a feature at this point. 
It feels with smart contacts being deterministic and simple by design such a use case is not very common.

Closing for now, feel free to reopen if you would like to add more to the discussion.

**Closed by marekkirejczyk** 2020-09-22 09:41 UTC

**Comment by jtremback** [comment] 2021-01-12 00:42
@marekkirejczyk I also have a use for this. I am testing a contract that deploys another contract and then emits its address along with other data. I cannot test the event with the current .withArgs matcher.

**Comment by jtremback** [comment] 2021-01-12 22:00
I have now written a function in my code which extracts the event arguments in the same way as the withArgs matcher. I then all of the arguments except the one i don't know ahead of time.

I don't know if this fits within the chai philosophy, but a useful matcher would be something that extracted the arguments in the event and allowed the user to check them in more detail, possibly within a closure or something.

**Comment by rad-p** [comment] 2021-04-22 11:52
I also do have a use case for such feature;

for example -- to mock uniswap router swap method -- [deadline](https://uniswap.org/docs/v2/smart-contracts/router02/#swapexacttokensfortokens) arg has to be set. Which will be equal to block timestamp at the moment of test execution, so is not deterministic. 

Wildcard arg match in mock setup, would be sufficient to cover the issue.

**Comment by vertti** [comment] 2022-03-17 06:11
The above examples should be enough to reopen this.
